# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02476616fb0f15fe9c791b1797ba92342d32faf7b8738b552752cf5367d50061a55b11da067ec06d82812323cdb066fa6394bee728a5a48e2d4bca92d96f5fa0

test:
  secret_key_base: defedfeb792c9c551d9e0563d6f5289e2a87d2c59d76534b2b056f51f1bf38d811f43e302556a467201a06908efc79c3d58745d6a2f7c556fcb31e8d59fb2f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
